### ISSUE TITLE
Why is the normalized mel inversed in am_inference?

### ISSUE THREAD

**Issue by wangyanbn** [PaddlePaddle/PaddleSpeech#2023]
Hi, I have a question:
In the forward() of FastSpeech2Inference , the normalized mel is inversed:
https://github.com/PaddlePaddle/PaddleSpeech/blob/05fd9a0e2ccdf5d3ca0e4da15c26cb4533889870/paddlespeech/t2s/models/fastspeech2/fastspeech2.py#L818

In paddlespeech\t2s\exps\synthesize.py,  use this inversed mel to infer: 
https://github.com/PaddlePaddle/PaddleSpeech/blob/05fd9a0e2ccdf5d3ca0e4da15c26cb4533889870/paddlespeech/t2s/exps/synthesize.py#L111

But when training voc model, the input mel is normalized :
https://github.com/PaddlePaddle/PaddleSpeech/blob/05fd9a0e2ccdf5d3ca0e4da15c26cb4533889870/examples/aishell3/voc1/local/train.sh#L9

Why is the normalized mel inversed in am_inference?

I guess, the pretrained voc model is trained use unnormalized mel, so it must be inversed in am_inference.

When training  voc model, we should use the normalized mel, right?

@yt605155624

**Comment by yt605155624** [comment]
We train am and voc both with normalized mel.

In voc's forward, we also have a norm step, see:

https://github.com/PaddlePaddle/PaddleSpeech/blob/05fd9a0e2ccdf5d3ca0e4da15c26cb4533889870/paddlespeech/t2s/models/hifigan/hifigan.py#L726

If you use am and voc trained with the same dataset(for example CSMSC), you can remove the denorm of am_inference and the norm of voc_inference, because the mean and std may be the same for the same dataset.

But if you want to use am trained with CSMSC but the voc trained with AISHELL3, you should first denorm am output with CSMSC's stats and norm it with AISHELL3's stats and input it to voc, if you want to remove denorm and norm, you may get bad result, because CSMSC and AISHELL3 have different stats(mean and std).

**Comment by wangyanbn** [comment]
I got it, Thanks!
I missed the code of forward in <voc>Inference class.
The mel is normalized before call the generator.inference
