### ISSUE TITLE
OSError: (External) CUFFT error(50).

### ISSUE THREAD

**Issue by pkuCactus** [PaddlePaddle/PaddleSpeech#2580]
The enviroment is cuda 10.2 cudnn 7.6, report the error while i run the command `paddlespeech cls --input dog.wav --device gpu:0`
The output as below:
```
W1024 12:42:32.074532 13131 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.7, Runtime API Version: 10.2
W1024 12:42:32.078289 13131 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.

You are running using the stub version of cufft
OSError: (External) CUFFT error(50).
  [Hint: Please search for the error code(50) on website (https://docs.nvidia.com/cuda/cufft/index.html#cufftresult) to get Nvidia's official solution and advice about CUFFT Error.] (at /paddle/paddle/fluid/operators/spectral_op.cu.h:84)
  [operator < fft_r2c > error].
```

Any suggest for this problem?

**Comment by yt605155624** [comment]
What's your paddlepaddle's version?

**Comment by pkuCactus** [comment]
the version is 2.3.1

**Comment by yt605155624** [comment]
I haven't met this error, it may caused by this `Driver API Version: 11.7, Runtime API Version: 10.2`, it means your CUDA driver version is `11.7` but you installed paddlepaddle for CUDA `10.2`, try to install paddlepaddle for cuda `11.6`, https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/24568452/197666331-72a4ddc0-fce4-421c-ac06-97d028669463.png">

**Comment by pkuCactus** [comment]
Thanks for your promptly reply.  I'll try it.

**Comment by chxx** [comment]
解决了吗？
