### ISSUE TITLE
decoders/swig的 setup.sh下载 kenlm的git地址没了吗 

### ISSUE THREAD

**Issue by lgd123** [PaddlePaddle/PaddleSpeech#465]
https://github.com/luotao1/kenlm.git  我在家里访问这个地址 一直是404.。。。怎么办  本人新手，是作者删除了 还是我被墙了

**Comment by zhupengyang** [comment]
这是是个人的repo，可能被删了。这个问题我们尽快确认下

**Comment by lgd123** [comment]
@zhupengyang  谢谢 大哥，我是新手  安装了3天没安装好...我用的是vmware虚拟机 安装的Ubuntu，安装出现了各种问题，swig出问题，安装openFst出问题，主要是openFst安装不上。我刚接触Python     我想问问，
1.vmware环境下 可以运行无gpu本项目吗。。
2.vmware环境下 无gpu,可以用Docker那个版本运行DeepSpeech吗 
没Docker，手头没有真实linux机器  运行 DeepSpeech有点难。。呜呜

**Comment by zhupengyang** [comment]
> 1.vmware环境下 可以运行无gpu本项目吗。。
> 2.vmware环境下 无gpu,可以用Docker那个版本运行DeepSpeech吗

理论上都是可以的~

**Comment by Aionrichman** [comment]
@zhupengyang 请问这个git什么时候能好啊

**Comment by rinjac** [comment]
@zhupengyang  @Aionrichman I fixed this issue by referencing the original KenLM repository (https://github.com/kpu/kenlm) instead of the unavailable one. For what I am using it, it works, but the creators need to confirm if the now unavailable repo (https://github.com/luotao1/kenlm.git) contained something which is not present in the original KenLM repo.

I created a pull request #464 which contains my fix.

**Comment by yeyupiaoling** [comment]
@Aionrichman @lgd123 已经修复啦，看新脚本代码，
https://github.com/PaddlePaddle/DeepSpeech/blob/b3c728d46ff4eee68c45f20b0abb76e968008bcb/decoders/swig/setup.sh#L3-L9
